config/routes.rb
Owl::Application.routes.draw do
  devise_for :users

  root to: 'lists#index', as: 'home'

  resources :lists, only: [:show, :edit, :update, :destroy, :new] do
    resource :love, only: [:create, :destroy]
    resources :loves, only: [:index]
    resources :comments, only: [:index, :create, :destroy]
    resources :items, only: [:destroy, :update, :create, :edit]
  end

  resources :reports, only: :create

  match '/about', to: 'pages#about', via: 'get', as: :about
  match '/legal', to: 'pages#legal', via: 'get', as: :legal
  match '/robots.txt', to: 'pages#robots', via: 'get', as: :robot

  resources :users, path: '', only: [:show, :edit, :update] do
    resource :love, only: [:create, :destroy]
    resource :follow, only: [:create, :destroy]
    resources :loves, only: [:index]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end
end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  TYPES = [ :text, :image, :link ]

  embedded_in :list
  validate :must_not_be_empty, on: :update
  validates_presence_of :type
  validates_length_of :name, maximum: 250, allow_blank: true
  validates_length_of :text, maximum: 1000, allow_blank: true
  validates_length_of :link, maximum: 2000, allow_blank: true
  after_validation :update_status, on: :update

  has_mongoid_attached_file :image,
    url: '/system/:class/:id/:basename-:style.:extension',
    default_url: '/assets/images/:style.jpg',
    styles: {
      small: ['120x120>',   :jpg],
      large: ['400x400>', :jpg] }
  validates_attachment_size :image, less_than: 800.kilobytes
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png', 'image/gif']
  validates_attachment_presence :image, on: :update, if: Proc.new { |m| m.image? }

  field :name,      type: String
  field :text,      type: String
  field :link,      type: String
  field :type,      type: Integer
  field :position,  type: Integer, default: 99999
  field :completed, type: Boolean, default: false

  def type_name
    TYPES.at(type)
  end

  def index
    list.items.index(self)
  end

  def text?
    type == TYPES.index(:text)
  end

  def image?
    type == TYPES.index(:image)
  end

  def link?
    type == TYPES.index(:link)
  end

  def link_valid?
    uri = URI.parse(link)
    uri.kind_of?(URI::HTTP||URI::HTTPS)
  rescue URI::InvalidURIError
    false
  end

private

  def must_not_be_empty
    case type
    when TYPES.index(:text)
      errors.add(:name, :name_or_text_missing) if name.blank? && text.blank?
    when TYPES.index(:link)
      errors.add(:link, :missing) if link.blank?
      errors.add(:link, :invalid) if !link.blank? && !link_valid?
    end
  end

  def update_status
    case type
    when TYPES.index(:text) then self.completed = !name.blank? || !text.blank?
    when TYPES.index(:image) then self.completed = true
    when TYPES.index(:link) then self.completed = !link.blank?
    else
      self.completed = false
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_filter :authenticate_user!
  before_filter :accpet_xhr_requests_only!

  def create
    @list = List.unscoped.find(params[:list_id])
    render inline: '0' and return unless is_list_owner?(@list)
    @item = @list.items.create(type: params[:type])
  end

  def edit
    list = List.unscoped.find(params[:list_id])
    render inline: '0' and return unless is_list_owner?(list)
    @item = list.items.find(params[:id])
  end

  def update
    list = List.unscoped.find(params[:list_id])
    render inline: '0' and return unless is_list_owner?(list)
    @item = list.items.find(params[:id])
    @item.assign_attributes(item_params)
    render :edit and return unless list.save
  end

  def destroy
    list = List.unscoped.find(params[:list_id])
    render inline: '0' and return unless is_list_owner?(list)
    @item = list.items.find(params[:id])
    @item.destroy
    list.save
  end

private

  def item_params
    params.require(:item).permit(:type, :name, :text, :link, :image)
  end
end

app/views/items/_edit_form.html.haml
%li.item{ class: item.type_name, id: "item_#{item.id}" }
  = render partial: "items/edit_#{item.type_name}_form", locals: { item: item }

app/views/items/_edit_image_form.html.haml
= minimal_form_for([item.list, item], remote: true, html: { id: "item_#{item.id}_form", multipart: true }) do |f|
  .imageInput
    %input{ name: 'item[image]', type: :file }
  .imagePreview
    .delete.fa.fa-times
    .files
      - if item.image.exists?
        = image_tag item.image.url(:small)
  = f.input :name
  = f.button :submit, t('.submit'), class: 'btn btn-primary submit'
  = link_to t('.delete'), list_item_path(item.list, item), remote: true, method: :delete, class: 'text-danger pull-right'

app/views/items/_edit_link_form.html.haml
= minimal_form_for([item.list, item], remote: true) do |f|
  = f.input :id, as: :hidden
  = f.input :list_id, as: :hidden, input_html: { value: item.list.id }
  = f.input :type, as: :hidden
  = f.input :name
  = f.input :link, as: :url, input_html: { value: item.link||'http://' }
  = f.button :submit, t('.submit'), class: 'btn btn-primary submit'
  = link_to t('.delete'), list_item_path(item.list, item), remote: true, method: :delete, class: 'text-danger pull-right'

app/views/items/_edit_text_form.html.haml
= minimal_form_for([item.list, item], remote: true) do |f|
  = f.input :id, as: :hidden
  = f.input :list_id, as: :hidden, input_html: { value: item.list.id }
  = f.input :type, as: :hidden
  = f.input :name
  = f.input :text, as: :text
  = f.button :submit, t('.submit'), class: 'btn btn-primary submit'
  = link_to t('.delete'), list_item_path(item.list, item), remote: true, method: :delete, class: 'text-danger pull-right'

app/views/items/_item.html.haml
%li.item{ class: item.type_name, id: "item_#{item.id}" }
  - if defined?(editable) && editable
    .tools
      = link_to t('.delete'), list_item_path(item.list, item), remote: true, method: :delete, class: 'text-danger'
      %span -
      = link_to t('.edit'), edit_list_item_path(item.list, item), remote: true
  - case item.type
  - when Item::TYPES.index(:text)
    = render partial: 'items/item_text', locals: { item: item.decorate }
  - when Item::TYPES.index(:image)
    = render partial: 'items/item_image', locals: { item: item.decorate }
  - when Item::TYPES.index(:link)
    = render partial: 'items/item_link', locals: { item: item.decorate }

app/views/items/_item_image.html.haml
= item.name
= item.image(:large)

app/views/items/_item_link.html.haml
= item.name
= item.link

app/views/items/_item_text.html.haml
= item.name
= item.text

app/views/items/_list.html.haml
%ol.items.list-unstyled
  = render partial: 'items/item', collection: items, as: :item, cache: Proc.new{|item| ['items/item', item]}

app/views/items/_new_form.html.haml
%div#item_new_form.btn-group.btn-group-justified
  - Item::TYPES.each_with_index do |type, i|
    = link_to t(".#{type}"), list_items_path(list_id: list.id, type: i), method: :post, remote: true, class: "btn btn-default #{type}"

app/views/items/create.js.erb
var item = $("<%= escape_javascript(render(partial: 'items/edit_form', locals: { item: @item })) %>");
$('#list_items_forms').append(item);
item.find('form').css('visibility', 'hidden');
item.hide().slideDown(function() {
  item.find('form').hide().css('visibility', 'visible').fadeIn();
});
<% if @item.image? %>
$('#item_<%= @item.id %>_form').itemEditImageForm({
    'url' : '<%= list_item_path(@item.list, @item) %>'
});
<% end %>

app/views/items/destroy.js.erb
var item = $("#item_<%= @item.id %>");
item.fadeOut(function() { $(this).remove(); });
$('#item_new_form .btn').removeClass('disabled');
$('#item_new_form').fadeIn();
<% if @item.list.completed %>
  $('#completed_button').removeClass('hidden');
<% else %>
  $('#completed_button').addClass('hidden');
<% end %>

app/views/items/edit.js.erb
var item = $("<%= escape_javascript(render(partial: 'items/edit_form', locals: { item: @item })) %>");
$('#item_<%= @item.id %>').replaceWith(item);
<% if @item.image? %>
$('#item_<%= @item.id %>_form').itemEditImageForm({
    'url' : '<%= list_item_path(@item.list, @item) %>'
});
<% end %>

app/views/items/new.js.erb
var item = $("<%= escape_javascript(render(partial: 'items/form_fields', locals: { item: @item })) %>");
$('<%= "#list_#{@list.id}_form .items" %>').append(item);
item.find('.fields').css('visibility', 'hidden');
item.hide().slideDown(function() {
  item.find('.fields').hide().css('visibility', 'visible').fadeIn();
  $('.list_form .item_types .btn').removeClass('disabled');
});