config/routes.rb
Owl::Application.routes.draw do
  devise_for :users

  root to: 'lists#index', as: 'home'

  resources :lists, only: [:show, :edit, :update, :destroy, :new] do
    resource :love, only: [:create, :destroy]
    resources :loves, only: [:index]
    resources :comments, only: [:index, :create, :destroy]
    resources :items, only: [:destroy, :update, :create, :edit]
  end

  resources :reports, only: :create

  match '/about', to: 'pages#about', via: 'get', as: :about
  match '/legal', to: 'pages#legal', via: 'get', as: :legal
  match '/robots.txt', to: 'pages#robots', via: 'get', as: :robot

  resources :users, path: '', only: [:show, :edit, :update] do
    resource :love, only: [:create, :destroy]
    resource :follow, only: [:create, :destroy]
    resources :loves, only: [:index]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end
end

app/views/layouts/_footer.html.haml
.container
  .row
    .col-sm-8
      %span= link_to t('.about'), about_path
      %span= link_to t('.legal'), legal_path
    .col-sm-4
      %small.text-muted copyright © OWL 2013-2014

app/views/layouts/_header.html.haml
#header

  .container

    .row

      .col-sm-3.col-xs-3
        = link_to 'OWL', home_path, class: 'logo'

      .col-sm-9.right
        = form_tag home_path, method: :get, class: 'search' do
          = hidden_field_tag :category_id, params[:category_id]
          .input-group
            %input#search_query.form-control{ name: 'query', placeholder: t('.search_placeholder'), type: 'search' }
            .input-group-btn
              %button.btn.btn-sm.btn-default.submit
                %i.fa.fa-search
        - if signed_in?
          = link_to user_path(current_user), class: 'visible-xs btn btn-sm btn-default user' do
            %i.fa.fa-user
          = link_to user_path(current_user), class: 'btn btn-sm btn-default hidden-xs' do
            = current_user.decorate.avatar_image :small
            = current_user.login
        - else
          %div.btn-group.sign
            = link_to t('.register_link'), new_user_registration_path(r: 1), class: 'btn btn-sm btn-default'
            = link_to t('.login_link'), new_user_session_path(r: 1), class: 'btn btn-sm btn-default'
        .tools
          - if signed_in?
            = link_to new_list_path, class: 'btn btn-sm btn-default create' do
              %span.hidden-xs= t('.create')
              %i.visible-xs.fa.fa-plus
          %button.btn.btn-sm.btn-default.categories-collapser{ 'data-toggle' => "collapse", 'data-target' => '#categories-collapse' }
            %i.fa.fa-bars

    %ul#categories-collapse.collapse.list-unstyled
      %li.category_999= link_to t('.all'), home_path
      - ListCategories.each_with_index do |category, i|
        %li{ class: "category_#{category[1]}" }= link_to List::category_name(category[1]), home_path(category_id: category[1])

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Owl
    = javascript_include_tag "vendor", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = stylesheet_link_tag "vendor", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cabin+Sketch:400,700'
    = csrf_meta_tags

  %body{ class: "#{request.parameters['controller']} #{request.parameters['action']}" }

    #main
      #top
        - cache ['v1', 'header', signed_in?, current_user||nil] do
          = render partial: 'layouts/header'
        - if request.parameters['controller'] == 'lists' && request.parameters['action'] == 'index'
          - cache ['v1', 'category', params[:category_id], signed_in?] do
            = render partial: 'lists/notes'

      = yield
      #push_footer

    - cache ['v1', 'footer'] do
      #footer
        = render partial: 'layouts/footer'

    %script
      = "window.owl.env['controller'] = '#{request.parameters['controller']}';"
      = "window.owl.env['action'] = '#{request.parameters['action']}';"
      = "window.owl.env['signed_in'] = #{signed_in?};"
      - if signed_in?
        - cache ['v1', current_user, 'envs'] do
          = "window.owl.env['current_user'] = '#{current_user.id.to_s}';"
          = "window.owl.env['followings'] = #{current_user.followings.to_s};".html_safe